all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
      ansible_host: 10.0.47.5
    serveur:
      ansible_host: 10.0.47.6
    serveur2:
      ansible_host: 10.0.47.7
